name: Android CI

on:
  push:
    branches:
      - main   # or master, adjust as per your repo
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (Gradle requires JDK 17 now)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload Debug APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
